### ISSUE TITLE
Pra onde tu vai ?

### ISSUE THREAD

**Issue by patrickmonteiro** [iagocavalcante/businessense#1]
Gostaria de saber para onde o senhor vai ?

**Comment by iagocavalcante** [comment]
hsuauhshuashusuhsahushuaush mds, me deixa

**Comment by patrickmonteiro** [comment]
Eu não consigo lhe abandonar amigo

![image](https://user-images.githubusercontent.com/13258255/87597955-174efc80-c6c9-11ea-879e-5efafae1b0bf.png)
